// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY00BJl6KDV2v0Y12JmXInMwoiPCRCIlc',
    appId: '1:725951764986:web:d0290a4292a182054c6c43',
    messagingSenderId: '725951764986',
    projectId: 'brinda-book',
    authDomain: 'brinda-book.firebaseapp.com',
    storageBucket: 'brinda-book.appspot.com',
    measurementId: 'G-05ZNR8WYF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJOVI7ztEZHnUsn1lCqgagEB4DIqcRlo',
    appId: '1:725951764986:android:8c4d7b1d8a0f57ef4c6c43',
    messagingSenderId: '725951764986',
    projectId: 'brinda-book',
    storageBucket: 'brinda-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV1yCVr7lJwY84tMaqdXuLIuD_Qk4jYwQ',
    appId: '1:725951764986:ios:2afeb51aedc398474c6c43',
    messagingSenderId: '725951764986',
    projectId: 'brinda-book',
    storageBucket: 'brinda-book.appspot.com',
    iosBundleId: 'com.richard.brindaBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV1yCVr7lJwY84tMaqdXuLIuD_Qk4jYwQ',
    appId: '1:725951764986:ios:2afeb51aedc398474c6c43',
    messagingSenderId: '725951764986',
    projectId: 'brinda-book',
    storageBucket: 'brinda-book.appspot.com',
    iosBundleId: 'com.richard.brindaBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY00BJl6KDV2v0Y12JmXInMwoiPCRCIlc',
    appId: '1:725951764986:web:95bb0c6dcfc4604f4c6c43',
    messagingSenderId: '725951764986',
    projectId: 'brinda-book',
    authDomain: 'brinda-book.firebaseapp.com',
    storageBucket: 'brinda-book.appspot.com',
    measurementId: 'G-WS4B1CYBYN',
  );
}
